@EventBooking.API_HostAddress = https://localhost:7030

GET {{EventBooking.API_HostAddress}}/api/events
Accept: application/json

###
GET {{EventBooking.API_HostAddress}}/api/events?skip=1&take=1
Accept: application/json

###
GET {{EventBooking.API_HostAddress}}/api/events?searchTerm=test2
Accept: application/json